# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.et_text = QtWidgets.QTextEdit(self.centralwidget)
        self.et_text.setGeometry(QtCore.QRect(10, 50, 540, 70))
        self.et_text.setObjectName("et_text")
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(10)
        self.et_text.setFont(font)
        self.et_morse_code = QtWidgets.QTextEdit(self.centralwidget)
        self.et_morse_code.setGeometry(QtCore.QRect(10, 160, 540, 70))
        self.et_morse_code.setObjectName("et_morse_code")
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(10)
        self.et_morse_code.setFont(font)
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(10, 10, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.text_label.setFont(font)
        self.text_label.setObjectName("text_label")
        self.morse_code_label = QtWidgets.QLabel(self.centralwidget)
        self.morse_code_label.setGeometry(QtCore.QRect(10, 130, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.morse_code_label.setFont(font)
        self.morse_code_label.setObjectName("morse_code_label")
        self.button_encode = QtWidgets.QPushButton(self.centralwidget)
        self.button_encode.setGeometry(QtCore.QRect(10, 240, 260, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_encode.setFont(font)
        self.button_encode.setObjectName("button_encode")
        self.button_decode = QtWidgets.QPushButton(self.centralwidget)
        self.button_decode.setGeometry(QtCore.QRect(290, 240, 260, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_decode.setFont(font)
        self.button_decode.setObjectName("button_decode")
        self.rb_en = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_en.setGeometry(QtCore.QRect(580, 80, 81, 41))
        self.rb_en.setObjectName("rb_en")
        self.rb_ru = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_ru.setGeometry(QtCore.QRect(580, 50, 91, 31))
        self.rb_ru.setObjectName("rb_ru")
        self.rb_ru.setChecked(True)
        self.language_label = QtWidgets.QLabel(self.centralwidget)
        self.language_label.setGeometry(QtCore.QRect(570, 10, 170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.language_label.setFont(font)
        self.language_label.setObjectName("text_label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_encode.clicked.connect(self.encode_to_morse)
        self.button_decode.clicked.connect(self.decode_from_morse)

    def decode_from_morse(self):
        if self.rb_ru.isChecked():
            try:
                code = self.et_morse_code.toPlainText().split()
                decode = ''
                for elem in code:
                    for key, codex in MORSE_CODE_RU.items():
                        if elem == codex:
                            decode += key
                self.et_text.setText(decode.capitalize())
            except TypeError:
                pass
        elif self.rb_en.isChecked():
            try:
                code = self.et_morse_code.toPlainText().split()
                decode = ''
                for elem in code:
                    for key, codex in MORSE_CODE_EN.items():
                        if elem == codex:
                            decode += key
                self.et_text.setText(decode.capitalize())
            except TypeError:
                pass

    def encode_to_morse(self):
        if self.rb_ru.isChecked():
            try:
                text = self.et_text.toPlainText().lower()
                encode = []
                for char in text:
                    encode.append(MORSE_CODE_RU.get(char))
                self.et_morse_code.setText(' '.join(encode))
            except TypeError:
                pass
        elif self.rb_en.isChecked():
            try:
                text = self.et_text.toPlainText().lower()
                encode = []
                for char in text:
                    encode.append(MORSE_CODE_EN.get(char))
                self.et_morse_code.setText(' '.join(encode))
            except TypeError:
                pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_label.setText(_translate("MainWindow", "Text:"))
        self.morse_code_label.setText(_translate("MainWindow", "Morse code:"))
        self.button_encode.setText(_translate("MainWindow", "ENCODE"))
        self.button_decode.setText(_translate("MainWindow", "DECODE"))
        self.rb_en.setText(_translate("MainWindow", "En"))
        self.rb_ru.setText(_translate("MainWindow", "Ru"))
        self.language_label.setText(_translate("MainWindow", "Language:"))

    def add_functions(self):
        self.decode_button.clicked.connect(self.decode_from_morse)
        self.encode_button.clicked.connect(self.encode_to_morse)

